### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by nijunssdut** [carrie0307/ace2005parser#1]
你好，我看您使用的是ACE2005英文的数据集，请问您有中文的数据集吗？本人在做这方面相关的工作，发现数据集不容易获取，希望能从您这边得到ACE2005中文事件抽取的数据集，万分感谢～

**Comment by carrie0307** [comment]
您好，抱歉刚刚才看到您的issue。由于licence限制，不能将数据直接分享给您，请见谅。
